name: greenspace_env
channels:
    - conda-forge #Ensures all packages come from conda-forge. Needed for osmnx
dependencies:
    - python=3.10
    - osmnx #osm data module
    - geopandas #osmnx support
    - matplotlib  #For visualization
    - requests #to pull from webpages
    - scipy.stats #potentially need this for additional correlation calculations
    - mock # To support unit tests using mock object library. 
    - geonamescache=2.2.0 #Geonames data for continents, cities and US states
